# Generated by Django 2.2.4 on 2019-08-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tausencia', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ausencia', models.IntegerField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('personat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.PersonaTabla')),
                ('tausenciat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tausencia.TipoAusencia')),
            ],
        ),
    ]
